---
title: "Projects, Grants & Policy Reports"
listing:
  - id: SLR
    contents: "SLR/*/index.qmd"
    sort: "date desc"
    date-format: "MMMM, YYYY"
    categories: false
    type: default
  - id: Climate_security_EP
    contents: "Climate_security_EP_2021/index.qmd"
    sort: "date desc"
    date-format: "MMMM, YYYY"
    categories: false
    type: default
  - id: FRM_UK
    contents: "FRM_UK_2021-present/index.qmd"
    sort: "date desc"
    date-format: "MMMM, YYYY"
    categories: false
    type: default
page-layout: full
title-block-banner: "#c27e97"
include-back-link: false
toc-location: right
---

In the past few years, I have been working on projects dealing with climate change adaptation. These projects have resulted in policy reports aimed at practitioners, who were also often involved in the design of the research. The common theme of these projects is the interplay between climate risks and the policy and political implications of adaptation, the decisions to be made and how those affect the existing balance between winners and losers.

::: panel-tabset
### Flood risk management

::: {#FRM_UK}
:::

### Climate and security

Thus far I have only worked on this topic for one project, linked below.

::: {#Climate_security_EP}
:::

### Sea level rise adaptation

This section lists the projects I have been involved in that concern the governance of climate adaptation to sea level rise. I began working on climate adaptation during my post-doc at University of California, Davis.

::: {#SLR}
:::
:::
