project:
  type: website
  output-dir: docs
  
website: 
  title: "Francesca Pia Vantaggiato"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research/index.qmd
        text: Research
      - href: cv/index.qmd
        text: CV
      - href: Projects.qmd
        text: Projects
      - href: Teaching/index.qmd
        text: Teaching
    right:
      - icon: github
        href: https://github.com/francescavantaggiato
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/FPVantaggiato
      - icon: linkedin
        href: https://www.linkedin.com/in/francesca-pia-vantaggiato/

format:
  html:
    theme: styles.scss
    toc: true
    
    
editor: visual

