---
title: "Sea-level rise adaptation and collaboration in polycentric governance: A comparison of three regions"
subtitle: "2026, *Public Administration Review*"
date: 2026-03-17
date-format: "MMMM, YYYY"
title-block-banner: false
author:
  - name: Francesca Pia Vantaggiato
    url: https://francescavantaggiato.github.io
    affiliation: Department of Political Economy, King's College London, United Kingdom
  - name: Mark Lubell
    url: https://environmentalpolicy.ucdavis.edu/
    affiliation: Department of Environmental Science & Policy, University of California Davis, United States
  - name: Matthew C. Nowlin
    affiliation: University of Texas at Arlington, United States
  - name: Juita-Elena (Wie) Yusuf
    affiliation: Old Dominion University, United States
  - name: Majid Shafiee-Jood
    affiliation: University of Virginia, United States
categories:
  - climate adaptation
  - collaborative governance
  - sea level rise
---

### Abstract

Adaptation to sea-level rise confronts coastal communities worldwide with a new set of collective action problems that require collaboration. When does collaboration result in concrete action for adaptation? To address this question, we combine the Ecology of Games and Collaborative Governance frameworks using a comparative analysis of three coastal regions in the United States. We leverage original survey data from the San Francisco Bay Area in California (2018, N = 878), the Tri-County (Charleston) Area in South Carolina (2022, N = 152), and the Hampton Roads region in Virginia (2023, N = 153), three regions that differ in terms of vulnerability, institutional capacity, and political culture. Across all three regions, we find that collaboration in sea-level rise adaptation is driven by a core set of high-capacity actors who build and participate across multiple planning forums in polycentric governance arrangements.

### Citation

``` bibtex
@article{PAR26,
    author = {Francesca Pia Vantaggiato and Mark Lubell and Matthew C. Nowlin and Juita-Elena Yusuf and Majid Shafiee-Jood},
    title = {Sea-level rise adaptation and collaboration in polycentric governance: A comparison of three regions},
    journal = {Public Administration Review},
    year = {2026},
    doi = {10.1111/puar.70117}
}
```
