---
title: "Supervision"
page-layout: full
title-block-banner: "#f1c40f"
include-back-link: false
format: 
  html:
    code-fold: true
engine: knitr
include-in-header: 
        text: |
          <style>
          h3 {
          color: #949799;
          }
          </style>
---

<style>

title-block-header {
  margin-block-end: 1rem;
  position: relative;
  margin-top: -1px;
  height: 80px;
}

.quarto-title-banner {
  margin-block-end: 1rem;
  position: relative;
  margin-top: -20px;
  height: 85%;
}

</style>

I am interested in supervising doctoral and post-doctoral students who want to work on the politics of public policy, regulation, climate adaptation, or environmental governance using quantitative or mixed methods approaches.  

Below are the profiles of the doctoral and post-doctoral students I currently supervise, listed in order of seniority.

<!--  https://stackoverflow.com/questions/74162212/two-columns-layout-in-quarto -->

:::: {.columns}

::: {.column width="30%"}

### As primary supervisor

---------------------------

**Santiago Quintero**

Santiago's doctoral studies are funded by a London Interdisciplinary Social Science Doctoral Training Partnership (LISS-DTP) scholarship for 2021-2024. 

His dissertation investigates the effects of political patronage on environmental governance networks in the public sector in Colombia.

[Santiago's personal website](https://squinterosuarez.com/)


---------------------------

**Yuetong Guo**

Yuetong's joined King's as a PhD student in 2022. 

Her dissertation focuses on the impact of inter-institutional relationships between the Council, the Parliament and the Commission on the EU's stance on global climate issues.

[Yuetong's webpage](https://www.kcl.ac.uk/people/yuetong-guo)

---------------------------


**Anna Goodden**

Anna's doctoral studies are funded by a LISS-DTP CASE studentship we obtained in collaboration with the Environment Agency for 2023-2026. 

Her dissertation focuses on resilience in the context of flood risk management in England: how to define and measure it, and what are the implications of different approaches.

[Anna's webpage](https://www.kcl.ac.uk/people/anna-goodden)

---------------------------

**William Edmonds**

William's doctoral studies are funded by a London Interdisciplinary Social Science Doctoral Training Partnership (LISS-DTP) scholarship for 2024-2027.

William's dissertation will focus on the evolution of transportation policy in the UK from the privatizations of the 1980s till the present day, and their effect on social mobility.

[Will's webpage](https://www.kcl.ac.uk/people/will-edmonds)

:::

::: {.column width="5%"}
<!-- empty column to create gap -->
:::

::: {.column width="30%"}
### As secondary supervisor

---------------------------

**Matteo Nebbiai**

Matteo's doctoral studies are funded by a London Interdisciplinary Social Science Doctoral Training Partnership (LISS-DTP) scholarship for 2022-2025. 

His dissertation focuses on the politics of regulating digital markets and data privacy in the EU.
[Matteo's personal website](https://www.matteonebbiai.site/)

:::

::: {.column width="5%"}
<!-- empty column to create gap -->
:::

::: {.column width="30%"}
### Post-docs

---------------------------

**Emma Yule** 

Emma joined King's in March 2024 as a post-doctoral researcher funded by a King's Climate & Sustainability Seed Grant that [James Porter](https://www.kcl.ac.uk/people/james-porter) and I won in December 2023. 

She works on climate adaptation barriers and solutions at local level with a particular focus on Scotland. 

[Emma's Google Scholar page](https://scholar.google.com/citations?user=0cU_xl0AAAAJ&hl=en)
:::

::::








:::